<!DOCTYPE html>
<head>
<meta charset="utf-8"/>
<title>國立聯合大學文創系莊明依作品集</title>
</head>
<body>
<center>
<div id="head">
<table width="1000" border="0" cellpadding="0"cellspacing="0">
<tr>
<td><img src="https://img.alicdn.com/imgextra/i3/1651938632/TB2o.e6bcUrBKNjSZPxXXX00pXa_!!1651938632-0-beehive-scenes.jpg_2200x2200Q50s50.jpg"width="1000" height="500"></td>
</tr>
<tr>
<td align="center">國立聯合大學文創系莊明依作品集</td>
</tr>


<div id="nav1"><br>

<table width="1000" border="0" cellpadding="0"cellspacing="1" bgcolor="#ffffff">

<tr>
<td align="left" bacolor="fffffff"><a href="index.htm">作品集</a>　＞<a href="index.htm">電繪作品</a>　＞
photoshop
</td>
</tr>

</table>
</div>



<div id="cont"><br>
<table width="1000" border="0" cellpadding="0"cellspacing="1" bgcolor="#999999">

<tr>
<td align="center"bgcolor="#ffffff" colspan="2"><h1>電繪作品</h1>
</td>
</tr>
<tr valign="top">
<td bgcolor="#ffffff" width="191"><table width="181">
<tr><td><a href="_blank"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2805_7365018_05613.jpg"></a></td></tr>
<tr><td><a href="_blank"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2811_1663698_05914.jpg"></a></td></tr>
<tr><td><a href="_blank"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2812_6598392_06210.jpg"></a></td></tr>
<tr><td><a href="_blank"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2807_8805083_06340.jpg"></a></td></tr>
<tr><td><a href="_blank"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2808_7596863_06584.png"></a></td></tr>
<tr><td><a href="_blank"><img src="https://hss.nuu.edu.tw/var/file/20/1020/plugin/mobile/title/hln_2810_8056118_06937.jpg"></a></td></tr>
</table></td>
<td bgcolor="#ffffff" width="806"><table width="800"><tr>

<tr>
<td><img width="145" height="200"src="https://www.heoseo.com/wp-content/uploads/2020/05/2016072516155072572.jpg"></td>
<td><img width="145" height="200"src="https://www.heoseo.com/wp-content/uploads/2020/05/2016072516155072572.jpg"></td>
<td><img width="145" height="200"src="https://www.heoseo.com/wp-content/uploads/2020/05/2016072516155072572.jpg"></td>
<td><img width="145" height="200"src="https://www.heoseo.com/wp-content/uploads/2020/05/2016072516155072572.jpg"></td>
<td><img width="145" height="200"src="https://www.heoseo.com/wp-content/uploads/2020/05/2016072516155072572.jpg"></td>
</tr>
<tr>
<td align="center"><a href="index.htm"target="_blank">第一個作品</td>
<td align="center"><a href="index.htm"target="_blank">第二個作品</td>
<td align="center"><a href="index.htm"target="_blank">第三個作品</td>
<td align="center"><a href="index.htm"target="_blank">第四個作品</td>
<td align="center"><a href="index.htm"target="_blank">第五個作品</td>
</tr>

<tr>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2016-7/2016072516164791070.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2016-7/2016072516164791070.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2016-7/2016072516164791070.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2016-7/2016072516164791070.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2016-7/2016072516164791070.jpg"></td>
</tr>
<tr>
<td align="center"><a href="index.htm"target="_blank">第六個作品</td>
<td align="center"><a href="index.htm"target="_blank">第七個作品</td>
<td align="center"><a href="index.htm"target="_blank">第八個作品</td>
<td align="center"><a href="index.htm"target="_blank">第九個作品</td>
<td align="center"><a href="index.htm"target="_blank">第十個作品</td>
</tr>

<tr>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2018-1/15173691026601484.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2018-1/15173691026601484.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2018-1/15173691026601484.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2018-1/15173691026601484.jpg"></td>
<td><img width="145" height="200"src="https://pic.qqtn.com/up/2018-1/15173691026601484.jpg"></td>
</tr>
<tr>
<td align="center"><a href="index.htm"target="_blank">第十一個作品</td>
<td align="center"><a href="index.htm"target="_blank">第十二個作品</td>
<td align="center"><a href="index.htm"target="_blank">第十三個作品</td>
<td align="center"><a href="index.htm"target="_blank">第十四個作品</td>
<td align="center"><a href="index.htm"target="_blank">第十五個作品</td>
</tr>



</tr>
</tr></table></td>
</table>
</div>
<br />
<div id="bottom">
  <table width="1000" border="0" cellpadding="0" cellspacing="1" bgcolor="#999999">
    <tr>
      <td align="center" bgcolor="#FFFFFF"><br />
        &copy版權所有。國立聯合大學文創系。禁止轉貼<br />
          <br />
        </a></td>
    </tr>
  </table>
</div>









</body>
</html>
